### ISSUE TITLE
'EasyLayout.h' file not found

### ISSUE THREAD

**Issue by houxinjie** [Instrument/Vicinity#1]
Hi,

After I download the project and build in the xcode, it has a error, do I miss some files?

**Comment by gettersetter** [comment]
I am having the same issue. missing EasyLayout.h and warning (Missing dependency target "EasyLayoutLibrary(from EasyLayout.xcodeproj).

**Comment by bentford** [comment]
Oops.  I forgot to include the EasyLayout project as a git submodule.  This is now checked in.
