### ISSUE TITLE
Problem ranging real iBeacons

### ISSUE THREAD

**Issue by omergul** [Instrument/Vicinity#2]
Hi,
It looks like there is a problem when detecting the real iBeacon signals. When two instances of Vicinity is running on different devices (one for advertising and one for detecting) they see each other. However, when I use a real iBeacon, Vicinity can not detect the signals. It is always out of range. I did not forget to provide the correct "SINGLETON_IDENTIFIER" value for estimate beacons. This is also true for advertising. Vicinity signals can not be detected as iBeacon signals (as an example, can'be detected by Estimote app). So is this example only meant to work with "Vicinity way" of beacons or am I missing out something?

**Comment by bentford** [comment]
Vicinity was not intended to interact with official iBeacon implementation and the identifiers not going to match what iBeacon is looking for.  It may be adjusted to work though.  

Here's how: OSX doesn't officially work with iBeacon yet but it's easy to make it work using CoreBluetooth.  Check out this article: https://github.com/mttrb/BeaconOSX

That was the inspiration for doing what Vicinity does.  Hope that helps.

**Comment by infoquestsolutions** [comment]
Hi Bentford

I am trying to use your application with passbook apps but its not working in background . I have changed UUID to match with pass and implemented the approach for creating dictionary here http://www.blendedcocoa.com/blog/2013/11/02/mavericks-as-an-ibeacon/  . Earlier your code was not working with passbook but after implementing it is working in foreground but not in background.

Thanks
Gaurav

**Comment by bentford** [comment]
@infoquestsolutions Try again with iOS7.1 as it has better support for background detection of beacons.
