### ISSUE TITLE
Detecting background broadcast while in the background

### ISSUE THREAD

**Issue by kennypolk** [Instrument/Vicinity#3]
I'm having an issue detecting another device while both devices are in the background. 

I start one device and lock it, having it detect in the background. I start the app on the other device, having it broadcast in the foreground. Detecting device finds the broadcast, great. 

Then comes my problem: 

I restart the device in the background. This time I have the second device broadcast while in the background. The detecting device is not able to find it. 

Have you encountered this problem? Any ideas?

Thanks

**Comment by mchambers** [comment]
Per the CoreBluetooth docs, the service ID would be moved into the overflow area when the broadcasting app is backgrounded.

See: https://developer.apple.com/library/ios/documentation/CoreBluetooth/Reference/CBPeripheralManager_Class/Reference/CBPeripheralManager.html#//apple_ref/occ/instm/CBPeripheralManager/startAdvertising:

**Comment by bentford** [comment]
iOS7.1 has improved support for background operations.  I haven't tried Vicinity out, but a few other people have reported good results with detecting in the background.
