### ISSUE TITLE
Support for iOS Simulator

### ISSUE THREAD

**Issue by objectiveSee** [Instrument/Vicinity#4]
I am unable to toggle into broadcast mode in the iOS Simulator. Looking at the code, it seems that since both isDetecting and isBroadcasting are false, nothing happens when you tap the toggle button.

see - (void)didToggleMode:(UIButton *)button

**Comment by bentford** [comment]
It doesn't look like low-energy Bluetooth is supported in iOS7 simulator.  http://stackoverflow.com/questions/10024608/does-the-iphone-simulator-in-xcode-support-bluetooth-low-energy

**Comment by objectiveSee** [comment]
Thanks @bentford
