### ISSUE TITLE
Broadcast/Detect simultaneously

### ISSUE THREAD

**Issue by gian-reto** [Instrument/Vicinity#7]
Hi,

is it possible to broadcast and detect with a device simultaneously? I was just wondering while studying the code...

Thank you for a reply :)

**Comment by objectiveSee** [comment]
yes, that is possible. I have done it with another app.

**Comment by bentford** [comment]
Sure. This works by instantiating two separate instances of the INBeaconService, one for broadcast and one for detection.  In fact, you spin up a new service for each UDID that you are detecting.  In our bluetooth game we have 4 detectors and one broadcast on each device.
